/* Generated by Yosys 0.63 (git sha1 70a11c6bf0e8dd669f56c7da3587f78b405138e2, clang++ 17.0.0 -fPIC -O3) */

(* top =  1  *)
(* src = "dff.v:2.1-17.10" *)
module dff(din, clk, we, rst, q, qbar);
  (* src = "dff.v:3.11-3.14" *)
  input din;
  wire din;
  (* src = "dff.v:3.16-3.19" *)
  input clk;
  wire clk;
  (* src = "dff.v:3.21-3.23" *)
  input we;
  wire we;
  (* src = "dff.v:3.25-3.28" *)
  input rst;
  wire rst;
  (* src = "dff.v:4.16-4.17" *)
  output q;
  reg q;
  (* src = "dff.v:5.12-5.16" *)
  output qbar;
  wire qbar;
  (* src = "dff.v:7.1-15.4" *)
  wire _0_;
  wire _1_;
  (* src = "dff.v:7.1-15.4" *)
  always @(posedge clk)
    q <= _0_;
  assign _1_ = we ? (* src = "dff.v:11.14-11.16|dff.v:11.10-13.8" *) din : q;
  assign _0_ = rst ? (* src = "dff.v:8.9-8.12|dff.v:8.5-13.8" *) 1'h0 : _1_;
  assign qbar = ~(* src = "dff.v:16.19-16.21" *) q;
endmodule
